### ISSUE TITLE
modernize backend and frontend

### ISSUE THREAD

**Issue by umputun** [umputun/secrets#11]
I'd like to update backend's dependencies, switch to go.mod and simplify the build process with github actions. At the same time, it would be nice to update the frontend the same way.

@igoradamenko I have created a branch `modern` to work on this. If you have a moment could you pls take a look? For some reason one of the frontend dependencies not available of failed.  Not sure what exactly the issue but `docker build .` fails with

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout 6d71a658c61edb3090221579d8f97dbe086ba2ed
npm ERR! fatal: reference is not a tree: 6d71a658c61edb3090221579d8f97dbe086ba2ed
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-19T06_07_17_133Z-debug.log
```

**Comment by igoradamenko** [comment]
Check this commit: deecf9c5135e85b2eba5e723006614870156a727, please. I works on my local machine. 

Still doesn't work in GitHub Actions though, but looks like something went wrong with Go: https://github.com/umputun/secrets/runs/454658211?check_suite_focus=true

**Comment by igoradamenko** [comment]
Ah, I guess you also wanted me to set up frontend building stage in Actions, right?

**Comment by umputun** [comment]
don't worry about actions, I'll take care. However (without actions) it still failing in docker build

```
> secrets-ui@0.2.1 build /srv/frontend
> gulp build

sh: gulp: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! secrets-ui@0.2.1 build: `gulp build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the secrets-ui@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-19T07_39_36_855Z-debug.log
The command '/bin/sh -c cd /srv/frontend &&     npm i --productio
```

**Comment by umputun** [comment]
adding `npm i gulp-install` seems to install gulp and build passes. Not sure if this is the blessed way as it complains about a deprecated package

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

**Comment by igoradamenko** [comment]
`gulp-install` is weird. It looks like someones semiprivate package that aims to “install everything at once”. Definitely shouldn't solve it this way.

It's strange that gulp wasn't found during Docker building phase. It should. But anyway, there're two ways to fix it: either use path to the gulp's binary file instead of `gulp` command, or install it globally (in container). I've chosen first way, it should work now, but I don't have Docker on my machine to check. It would be nice if you do it. If it doesn't work I will install Docker and try it by myself.

Here is the commit: 9ef6af2cec114403871a4c3e8ffba44d39752d5e

**Comment by umputun** [comment]
nop

```
> secrets-ui@0.2.1 build /srv/frontend
> gulp build

sh: gulp: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! secrets-ui@0.2.1 build: `gulp build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the secrets-ui@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by umputun** [comment]
The gulp (at least binary) doesn't seem to be part of this base image

```
docker run -it --rm node:10.19.0-alpine3.11 sh
/ # which gulp
/ # gulp
sh: gulp: not found
```

**Comment by umputun** [comment]
I have added `npm i gulp` to the Dockerfile and it seems to do it. Hopefully, this is the blessed way to install gulp ;)

**Comment by igoradamenko** [comment]
Yeah, it was the second way to fix it. 

Okay, great. Glad to hear that everything works.
